export const sidebarMenuItems = {
  top: [
    {
      iconUrl: "ph:sidebar-duotone",
      tooltipText: "Dashboard",
      menuTitle: "Dashboard",
      isSelected: true,
      hasSubMenu: true,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [
        {
          subMenuTitle: "Home",
          redirectUrl: "/dashboard",
          showDividerOnTop: false,
          showDividerOnBottom: true,
          isOpen: true,
          isSelected: true,
          hasSubMenu: false,
          subMenuItems: [],
        },
        {
          subMenuTitle: "Blogs",
          redirectUrl: "#",
          showDividerOnTop: false,
          showDividerOnBottom: false,
          isOpen: false,
          isSelected: true,
          hasSubMenu: true,
          subMenuItems: [
            {
              subMenuTitle: "Blogs",
              redirectUrl: "/blogs",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              isOpen: false,
              icon: "mdi:blog-outline",
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Manage Blogs",
              redirectUrl: "/manage-blogs",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "ix:product-management",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            }
          ]
        },
        {
          subMenuTitle: "Users",
          redirectUrl: "/users",
          showDividerOnTop: false,
          showDividerOnBottom: false,
          isOpen: true,
          isSelected: false,
          hasSubMenu: true,
          subMenuItems: [
            {
              subMenuTitle: "Customers",
              redirectUrl: "/website-customers",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              isOpen: true,
              icon: "clarity:users-solid",
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Website Leads",
              redirectUrl: "/website-leads",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "mdi:leads-outline",
              isOpen: true,
              isSelected: false,
              hasSubMenu: false,
            }
          ],
        },
        {
          subMenuTitle: "Analytics",
          redirectUrl: "#",
          showDividerOnTop: false,
          showDividerOnBottom: false,
          isOpen: false,
          isSelected: false,
          hasSubMenu: true,
          subMenuItems: [
            {
              subMenuTitle: "Store Analytics",
              redirectUrl: "/store-analytics",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "clarity:store-solid",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Live Analytics",
              redirectUrl: "/live-analytics",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "fluent:live-24-regular",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            }
          ]
        },
        {
          subMenuTitle: "Marketing",
          redirectUrl: "#",
          showDividerOnTop: false,
          showDividerOnBottom: false,
          isOpen: false,
          isSelected: false,
          hasSubMenu: true,
          subMenuItems: [
            {
              subMenuTitle: "Automation",
              redirectUrl: "/automation",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "fad:automation-3p",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Campaigns",
              redirectUrl: "/campaign",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "material-symbols:campaign-sharp",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            }
          ]
        },
        {
          subMenuTitle: "Integrations",
          redirectUrl: "#",
          showDividerOnTop: false,
          showDividerOnBottom: false,
          isOpen: false,
          isSelected: false,
          hasSubMenu: true,
          subMenuItems: [
            {
              subMenuTitle: "Social",
              redirectUrl: "/integration/social",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "tabler:social",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Lead",
              redirectUrl: "/integration/leads",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "mdi:leads",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Communication",
              redirectUrl: "/integration/leads",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "maki:communications-tower",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            }
          ]
        },
        {
          subMenuTitle: "Media Box",
          redirectUrl: "/media",
          showDividerOnTop: false,
          showDividerOnBottom: false,
          isOpen: false,
          isSelected: false,
          hasSubMenu: true,
          subMenuItems: [
            {
              subMenuTitle: "Images",
              redirectUrl: "/media/images",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              isOpen: false,
              icon: "humbleicons:images",
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Videos",
              redirectUrl: "/media/videos",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "lets-icons:video",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Documents",
              redirectUrl: "/media/documents",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "solar:document-outline",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            }
          ]
        },
      ],
    },
    {
      iconUrl: "ph:app-window-duotone",
      tooltipText: "Website Builder",
      menuTitle: "Website Builder",
      isSelected: false,
      hasSubMenu: true,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [
        {
          subMenuTitle: "Overview",
          redirectUrl: "/builder",
          showDividerOnTop: false,
          showDividerOnBottom: true,
          isOpen: false,
          isSelected: false,
          hasSubMenu: false,
          subMenuItems: [],
        },
        {
          subMenuTitle: "Builder",
          redirectUrl: "#",
          showDividerOnTop: false,
          showDividerOnBottom: false,
          isOpen: false,
          isSelected: true,
          hasSubMenu: true,
          subMenuItems: [
            {
              subMenuTitle: "Website",
              redirectUrl: "/builder",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              isOpen: false,
              icon: "gg:website",
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Pages",
              redirectUrl: "/builder/pages",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              isOpen: false,
              icon: "streamline:browser-website-1-solid",
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Navigation",
              redirectUrl: "/builder/menu",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "solar:menu-dots-circle-broken",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            }
          ]
        },
        {
          subMenuTitle: "Configration",
          redirectUrl: "#",
          showDividerOnTop: false,
          showDividerOnBottom: false,
          isOpen: false,
          isSelected: true,
          hasSubMenu: true,
          subMenuItems: [
            {
              subMenuTitle: "Theme",
              redirectUrl: "/builder",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              isOpen: false,
              icon: "ri:paint-brush-line",
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Template",
              redirectUrl: "/builder/pages",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              isOpen: false,
              icon: "icon-park-twotone:page-template",
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "SEO",
              redirectUrl: "/builder/menu",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "hugeicons:seo",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            },
            {
              subMenuTitle: "Settings",
              redirectUrl: "/builder/menu",
              showDividerOnTop: false,
              showDividerOnBottom: false,
              icon: "hugeicons:settings-04",
              isOpen: false,
              isSelected: false,
              hasSubMenu: false,
            }
          ]
        },
      ],
    },
    {
      iconUrl: "oui:documentation",
      tooltipText: "Documentation",
      menuTitle: "Documentation",
      isSelected: false,
      hasSubMenu: true,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [],
    },
  ],
  bottom: [
    {
      iconUrl: "ph:magnifying-glass-duotone",
      tooltipText: "Search",
      menuTitle: "",
      hasSubMenu: false,
      isPageNavigation: false,
      pageUrl: "#search",
      haveTrigger: true,
      trigger: "Globalsearch",
    },
    {
      iconUrl: "ph:gear-six-duotone",
      tooltipText: "Settings",
      menuTitle: "",
      hasSubMenu: false,
      isPageNavigation: true,
      pageUrl: "/company/settings",
      haveTrigger: false,
      trigger: "",
    },
  ],
};
