export const sidebarMenuItems = {
  top: [
    {
      iconUrl: "ph:sidebar-duotone",
      tooltipText: "Dashboard",
      menuTitle: "Dashboard",
      isSelected: true,
      hasSubMenu: true,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [
        {
          subMenuTitle: "Overview",
          redirectUrl: "/dashboard",
          showDividerOnTop: true,
          showDividerOnBottom: true,
          isOpen: true,
          isSelected: true,
          hasSubMenu: false,
          subMenuItems: [],
        },
      ],
    },
    {
      iconUrl: "ph:app-window-duotone",
      tooltipText: "Website Builder",
      menuTitle: "Website Builder",
      isSelected: false,
      hasSubMenu: true,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [
        {
          subMenuTitle: "Editor",
          redirectUrl: "/builder",
          showDividerOnTop: false,
          showDividerOnBottom: false,
          isOpen: false,
          isSelected: false,
          hasSubMenu: false,
          subMenuItems: [],
        },
      ],
    },
    {
      iconUrl: "oui:documentation",
      tooltipText: "Documentation",
      menuTitle: "Documentation",
      isSelected: false,
      hasSubMenu: true,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [],
    },
  ],
  bottom: [
    {
      iconUrl: "ph:magnifying-glass-duotone",
      tooltipText: "Search",
      menuTitle: "",
      hasSubMenu: false,
      isPageNavigation: false,
      pageUrl: "#search",
      haveTrigger: true,
      trigger: "Globalsearch",
    },
    {
      iconUrl: "ph:gear-six-duotone",
      tooltipText: "Settings",
      menuTitle: "",
      hasSubMenu: false,
      isPageNavigation: true,
      pageUrl: "/company/settings",
      haveTrigger: false,
      trigger: "",
    },
  ],
};
