export const sidebarBuilderMenuItems = {
  top: [
    {
      iconUrl: "lucide:square-plus",
      tooltipText: "Add elements",
      menuTitle: "Add elements",
      isSelected: true,
      hasSubMenu: false,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [],
    },
    {
      iconUrl: "mynaui:layout",
      tooltipText: "Layouts",
      menuTitle: "Layouts",
      isSelected: false,
      hasSubMenu: false,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [],
    },
    {
      iconUrl: "ic:outline-palette",
      tooltipText: "Themes",
      menuTitle: "Themes",
      isSelected: false,
      hasSubMenu: false,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [],
    },
    {
      iconUrl: "solar:file-bold",
      tooltipText: "Assets",
      menuTitle: "Assets",
      isSelected: false,
      hasSubMenu: false,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [],
    },
    {
      iconUrl: "mdi-light:image",
      tooltipText: "Images",
      menuTitle: "Images",
      isSelected: false,
      hasSubMenu: false,
      isPageNavigation: false,
      pageUrl: "",
      menuItems: [],
    },
  ],
  bottom: [
    {
      iconUrl: "line-md:alert-circle-loop",
      tooltipText: "Help",
      menuTitle: "Help",
      hasSubMenu: false,
      isPageNavigation: false,
      pageUrl: "#search",
      haveTrigger: true,
      trigger: "Globalsearch",
    },
    {
      iconUrl: "ph:gear-six-duotone",
      tooltipText: "Settings",
      menuTitle: "",
      hasSubMenu: false,
      isPageNavigation: true,
      pageUrl: "/company/settings",
      haveTrigger: false,
      trigger: "",
    },
  ],
};
